let storageBags = [
    { id: 1, name: "Black Genuine Leather Bags", price: "$23,20", type: "bag", img: "./img/product/bags/bagFirst.png", },
    { id: 2, name: "Fashion Red Leather Bags", price: "$20,16", type: "bag", img: "./img/product/bags/bagSecond.png", },
    { id: 3, name: "Fashion Genuine Leather Bags", price: "$30,14", type: "bag", img: "./img/product/bags/bagThird.png", },
    { id: 4, name: "New Fashion Leather Bags", price: "$25,20", type: "bag", img: "./img/product/bags/bagFourth.png", },
    { id: 5, name: "Single Hand Models Bags", price: "$17,61", type: "bag", img: "./img/product/bags/bagFifth.png", },
    { id: 6, name: "Simply Leather Bags ", price: "$15,22", type: "bag", img: "./img/product/bags/bagSixth.png", },
    { id: 7, name: "Fashion Genuine Leather Bags", price: "$30,14", type: "bag", img: "./img/product/bags/bagThird.png", },
    { id: 8, name: "Simply Leather Bags ", price: "$15,22", type: "bag", img: "./img/product/bags/bagSixth.png", },
    { id: 9, name: "Black Genuine Leather Bags", price: "$23,20", type: "bag", img: "./img/product/bags/bagFirst.png", },
    { id: 10, name: "Fashion Red Leather Bags", price: "$20,16", type: "bag", img: "./img/product/bags/bagSecond.png", },
    { id: 11, name: "New Fashion Leather Bags", price: "$25,20", type: "bag", img: "./img/product/bags/bagFourth.png", },
    { id: 12, name: "Single Hand Models Bags", price: "$17,61", type: "bag", img: "./img/product/bags/bagFifth.png", },
    { id: 13, name: "Single Hand Models Bags", price: "$17,61", type: "bag", img: "./img/product/bags/bagFifth.png", },
    { id: 14, name: "Black Genuine Leather Bags", price: "$23,20", type: "bag", img: "./img/product/bags/bagFirst.png", },
    { id: 15, name: "Fashion Red Leather Bags", price: "$20,16", type: "bag", img: "./img/product/bags/bagSecond.png", },
    { id: 16, name: "Fashion Genuine Leather Bags", price: "$30,14", type: "bag", img: "./img/product/bags/bagThird.png", },
    { id: 17, name: "New Fashion Leather Bags", price: "$25,20", type: "bag", img: "./img/product/bags/bagFourth.png", },
    { id: 18, name: "Single Hand Models Bags", price: "$17,61", type: "bag", img: "./img/product/bags/bagFifth.png", },
    { id: 19, name: "Simply Leather Bags ", price: "$15,22", type: "bag", img: "./img/product/bags/bagSixth.png", },
    { id: 20, name: "Fashion Genuine Leather Bags", price: "$30,14", type: "bag", img: "./img/product/bags/bagThird.png", },
    { id: 21, name: "Simply Leather Bags ", price: "$15,22", type: "bag", img: "./img/product/bags/bagSixth.png", },
    { id: 22, name: "Black Genuine Leather Bags", price: "$23,20", type: "bag", img: "./img/product/bags/bagFirst.png", },
    { id: 12, name: "Fashion Red Leather Bags", price: "$20,16", type: "bag", img: "./img/product/bags/bagSecond.png", },
    { id: 24, name: "New Fashion Leather Bags", price: "$25,20", type: "bag", img: "./img/product/bags/bagFourth.png", },
]

let storageWatch = [
    { id: 1, name: "Black Genuine Leather watch", price: "$25,20", type: "watch", img: "./img/product/watch/watchFirst.png", },
    { id: 2, name: "Fashion Red Leather watch", price: "$30,16", type: "watch", img: "./img/product/watch/watchSecond.png", },
    { id: 3, name: "Fashion Genuine Leather watch", price: "$30,14", type: "watch", img: "./img/product/watch/watchThird.png", },
    { id: 4, name: "New Fashion Leather watch", price: "$45,20", type: "watch", img: "./img/product/watch/watchFourth.png", },
    { id: 5, name: "Single Hand Models watch", price: "$17,67", type: "watch", img: "./img/product/watch/watchFifth.png", },
    { id: 6, name: "Simply Leather watch ", price: "$15,29", type: "watch", img: "./img/product/watch/watchSixth.png", },
    { id: 1, name: "Black Genuine Leather watch", price: "$25,20", type: "watch", img: "./img/product/watch/watchFirst.png", },
    { id: 2, name: "Fashion Red Leather watch", price: "$30,16", type: "watch", img: "./img/product/watch/watchSecond.png", },
    { id: 3, name: "Fashion Genuine Leather watch", price: "$30,14", type: "watch", img: "./img/product/watch/watchThird.png", },
    { id: 4, name: "New Fashion Leather watch", price: "$45,20", type: "watch", img: "./img/product/watch/watchFourth.png", },
    { id: 5, name: "Single Hand Models watch", price: "$17,67", type: "watch", img: "./img/product/watch/watchFifth.png", },
    { id: 6, name: "Simply Leather watch ", price: "$15,29", type: "watch", img: "./img/product/watch/watchSixth.png", },
    { id: 1, name: "Black Genuine Leather watch", price: "$25,20", type: "watch", img: "./img/product/watch/watchFirst.png", },
    { id: 2, name: "Fashion Red Leather watch", price: "$30,16", type: "watch", img: "./img/product/watch/watchSecond.png", },
    { id: 3, name: "Fashion Genuine Leather watch", price: "$30,14", type: "watch", img: "./img/product/watch/watchThird.png", },
    { id: 4, name: "New Fashion Leather watch", price: "$45,20", type: "watch", img: "./img/product/watch/watchFourth.png", },
    { id: 5, name: "Single Hand Models watch", price: "$17,67", type: "watch", img: "./img/product/watch/watchFifth.png", },
    { id: 6, name: "Simply Leather watch ", price: "$15,29", type: "watch", img: "./img/product/watch/watchSixth.png", },
    { id: 1, name: "Black Genuine Leather watch", price: "$25,20", type: "watch", img: "./img/product/watch/watchFirst.png", },
    { id: 2, name: "Fashion Red Leather watch", price: "$30,16", type: "watch", img: "./img/product/watch/watchSecond.png", },
    { id: 3, name: "Fashion Genuine Leather watch", price: "$30,14", type: "watch", img: "./img/product/watch/watchThird.png", },
    { id: 4, name: "New Fashion Leather watch", price: "$45,20", type: "watch", img: "./img/product/watch/watchFourth.png", },
    { id: 5, name: "Single Hand Models watch", price: "$17,67", type: "watch", img: "./img/product/watch/watchFifth.png", },
    { id: 6, name: "Simply Leather watch ", price: "$15,29", type: "watch", img: "./img/product/watch/watchSixth.png", },
]
